name: 生成天气预报m3u文件

on:
  schedule:
      # - cron: "17 20 * * *" # runs at 20:17 every day
      # - cron: "20 20 * * *" # runs at 20:20 every day
      - cron: "*/1 * * * *" # runs every 30 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Install dependencies
      #   run: npm install
      - name: Run Node.js script
        run: |
          node app.js > cctv_weather_forecasting.m3u
      # - name: Upload output file
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: cctv_weather_forecasting.m3u
      #     path: cctv_weather_forecasting.m3u
      - name: Upload output file to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @cctv_weather_forecasting.m3u \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/latest/assets?name=cctv_weather_forecasting.m3u"