name: Run Node.js script

on:
  schedule:
      - cron: "*/3 * * * *" # runs every 3 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Node.js script
        run: |
          node app.js > cctv_weather_forecasting.m3u8
      - name: Upload output file
        uses: actions/upload-artifact@v4
        with:
          name: cctv_weather_forecasting.m3u8
          path: cctv_weather_forecasting.m3u8
